

export const allpr=[
  {id:1, categorie:['all','react'],project:'Prayer Time website ',spn:'using React',img:'assets/images/prayer_app.jpeg',descreption:'built using React js library with Material UI design framework. This application displays react deferent states managment.'},
  {id:2, categorie:['all','react','Full'],project:'Fullstack Chat App',spn:'using Mern',img:'assets/images/chat_app1.jpeg',descreption:'build usinh MERN Stack Socket.io,For Styling we use TailwindCSS also i use  Daisy UI as design framework. '},
  {id:3, categorie:['all','mobile'],project:'Payment Flutter App ',spn:' Using Laravel',img:'assets/images/flutter_payment.jpeg',descreption:'Flutter mobile app developed using Laravel and as a state managment i used Getx . '},
  {id:4, categorie:['all','mobile'],project:'Learning App',spn:' for Special Needs Kids',img:'assets/images/flutter_quiz_app.jpg',descreption:'An application directed at children with Down Syndrome ,provide with sound, image, and writing.'},
  {id:5, categorie:['all','mobile'],project:'Taksk Managment App ',spn:' using Flutter and GO',img:'assets/images/flutter_task.jpeg',descreption:'Flutter mobile app developed using Go and Provider as a state managment .'},
  {id:6, categorie:['all','react','Full'],project:'Twitter Clone App ',spn:' Using Mern',img:'assets/images/twitter_clone.jpeg',descreption:'Mern web App contains a lot of modern technical features'},
  {id:7, categorie:['all','react','Full'],project:'Ecommerce App ',spn:'using Mern',img:'assets/images/ecommerce.jpeg',descreption:'Ecommerce Web App developed using Mern stack contains a lot of modern technical features .'},
  {id:8, categorie:['all','react'],project:'Todos App ',spn:' using React',img:'assets/images/todos.jpg',descreption:'Simple react todos app using deferent react concept like hooks and others .'},
  {id:9, categorie:['all','react'],project:'Candy Crash React Version',spn:' using React',img:'assets/images/react_js.png',descreption:'Candy Crash React Version we are using we have used in this version  react hooks and the interactive components'},
 {id:10, categorie:['all','react'],project:'Tic-Tac-Toe React Version',spn:' using React',img:'assets/images/tic_tac_react.jpg',descreption:'Tic-Tac-Toe using react Hooks include the interactive components that represent the board, the signs, and at last the winner of the game.'},
 
  {id:11, categorie:['all','mobile'],project:'Book Car Maintenance App ',spn:' Base on ML',img:'assets/images/car2.jpeg',descreption:'Providing a car maintenance book in the form of a mobile application, this application aims to periodically '},
  {id:12, categorie:['all','js'],project:'Snake Game ',spn:' using Js & Html & Css',img:'assets/images/snake01.png',descreption:'Classic snake game using pure JS, I did not use any framework or library , only relying on Grid CSS.'},
  {id:13, categorie:['all','js'],project:'Tic-Tac-Toe Game ',spn:'',img:'assets/images/tic_tac.jpg',descreption:'Tic Tac Toe Game developed using javascript Without using any library or framework, just relying on HTML and CSS.'},
  {id:14, categorie:['all','js'],project:'Rock paper scissors Game ',spn:'',img:'assets/images/paper.jpeg',descreption:'A Classic Rock paper scissors  game with HTML, CSS, and JavaScript.'},
  {id:15, categorie:['all','js'],project:'Memory Game App ',spn:' using Js & Html & Css ',img:'assets/images/memory_game01.jpeg',descreption:'Game developed using javascript Without using any library or framework, just relying on HTML and CSS.'},
  {id:16, categorie:['all','js'],project:'Quiz Game App ',spn:' using Js & Html & Css ',img:'assets/images/quiz.png',descreption:'A quis developed using javascript ,We designed the entire application using modern styling practices.'},
  {id:17, categorie:['all','js'],project:'Guess the word game ',spn:' using Js & Html & Css ',img:'assets/images/guess.jpeg',descreption:'Game developed using js Without using any library or framework, just relying on HTML and CSS.'},
  {id:18, categorie:['all','js'],project:'Candy Crush Game App ',spn:' using Js & Html & Css ',img:'assets/images/candy_crash.jpeg',descreption:'You try to form horizontal or vertical chains of at least three identical ones by swapping neighboring candies with each other'},
  {id:19, categorie:['all','js'],project:'Hangman Game App ',spn:' using Js & Html & Css ',img:'assets/images/hangman_js.png',descreption:'Is a game where we have a hidden word, and we need to guess it by clicking on individual letters.'},
   {id:20, categorie:['all','js'],project:'Pong Clone Game App ',spn:' using Js & Html & Css ',img:'assets/images/pang_clone.png',descreption:'Pong game is a two-player table tennis-themed game. The game involves two paddles and a moving ball'}, 
  {id:21, categorie:['all','mobile'],project:'Scheduled Notifications app using',spn:'Flutter',img:'assets/images/notifications.jpg',descreption:'App for iOS and Andoid Using Sqlite & Sqflite CRUD for database With local push notifications and getx as state managment .'},
  {id:22, categorie:['all','mobile'],project:'Video Player app using',spn:'Flutter',img:'assets/images/video.png',descreption:'I covered video player controls, aspect ratio, load videos from network using json files from network or url.'},   
]