

export const allpr=[
  {id:1, categorie:['all','react'],project:'Prayer Time website using React',img:'assets/images/prayer_app.jpeg',descreption:'built using React js library with Material UI design framework. This application displays react deferent states managment.'},
  {id:2, categorie:['all','react','Full'],project:'Fullstack Chat App using Mern',img:'assets/images/chat_app1.jpeg',descreption:'build usinh MERN Stack Socket.io,For Styling we use TailwindCSS also i use  Daisy UI as design framework. '},
  {id:3, categorie:['all','mobile'],project:'Payment App Using Flutter and Laravel',img:'assets/images/flutter_payment.jpeg',descreption:'Flutter mobile app developed using Laravel and as a state managment i used Getx . '},
  {id:4, categorie:['all','mobile'],project:'Learning App for Special Needs Kids',img:'assets/images/flutter_quiz_app.jpg',descreption:'An application directed at children with Down Syndrome ,provide with sound, image, and writing.'},
  {id:5, categorie:['all','mobile'],project:'Taksk Managment App using Flutter and GO',img:'assets/images/flutter_task.jpeg',descreption:'Flutter mobile app developed using Go and Provider as a state managment .'},
  {id:6, categorie:['all','react','Full'],project:'FullStack Twitter Clone App Using Mern',img:'assets/images/twitter_clone.jpeg',descreption:'Mern web App contains a lot of modern technical features'},
  {id:7, categorie:['all','react','Full'],project:'FullStack Ecommerce App using Mern',img:'assets/images/ecommerce.jpeg',descreption:'Ecommerce Web App developed using Mern stack contains a lot of modern technical features .'},
  {id:9, categorie:['all','react'],project:'Todos App using React',img:'assets/images/todos.jpg',descreption:'Simple react todos app using deferent react concept like hooks and others .'},
  {id:10, categorie:['all','mobile'],project:'Book Car Maintenance App Base on ML',img:'assets/images/car2.jpeg',descreption:'Providing a car maintenance book in the form of a mobile application, this application aims to periodically monitor the car and take care of maintenance dates by reminding maintenance dates, and technical changes that should be made according to the distance traveled based on a machine learning-based recommendation system model, through this project the user can extend the life of the car, reduce maintenance costs, and overall road safety. This application was programmed using the Flutter framework, State Management: Block, while the artificial intelligence aspect was programmed in Python language'},
  {id:12, categorie:['all','js'],project:'Snake Game using Js & Html & Css',img:'assets/images/snake01.png',descreption:'Classic snake game using pure JS, I did not use any framework or library , only relying on Grid CSS.'},
  {id:13, categorie:['all','js'],project:'Tic-Tac-Toe Game',img:'assets/images/tic_tac.jpg',descreption:'Tic Tac Toe Game developed using javascript Without using any library or framework, just relying on HTML and CSS.'},
  {id:14, categorie:['all','js'],project:'Rock paper scissors Game',img:'assets/images/paper.jpeg',descreption:'A Classic Rock paper scissors  game with HTML, CSS, and JavaScript.'},
  {id:15, categorie:['all','js'],project:'Memory Game App using Js & Html & Css ',img:'assets/images/memory_game01.jpeg',descreption:'Game developed using javascript Without using any library or framework, just relying on HTML and CSS.'},
  {id:16, categorie:['all','js'],project:'Quiz Game App using Js & Html & Css ',img:'assets/images/quiz.png',descreption:'A quis developed using javascript ,We designed the entire application using modern styling practices.'},
  {id:17, categorie:['all','js'],project:'Guess the word game using Js & Html & Css ',img:'assets/images/guess.jpeg',descreption:'Game developed using js Without using any library or framework, just relying on HTML and CSS.'},
  {id:18, categorie:['all','mobile'],project:'Flutter Scheduled Notifications app',img:'assets/images/notifications.jpg',descreption:'App for iOS and Andoid Using Sqlite & Sqflite CRUD for database With local push notifications and getx as state managment .'},
  {id:19, categorie:['all','mobile'],project:'Flutter Video Player app',img:'assets/images/video.png',descreption:'I covered video player controls, aspect ratio, load videos from network using json files from network or url.'},   
]