export const allpr=[
    {id:1, categorie:'all',project:'project 1',img:'../assets/images/'},
    {id:2, categorie:'all',project:'project 1',img:''},
    {id:3, categorie:'react',project:'Prayer Time website using React',img:'../assets/images/prayer_app.jpeg'},
    {id:4, categorie:'Full',project:'Fullstack Char app using Mern',img:'../assets/images/chat_app1.jpeg'},
    {id:5, categorie:'mobile',project:'Payment app Using Flutter and Laravel',img:'../assets/images/chat_app.jpg'},
    {id:6, categorie:'mobile',project:'Learning App for Special Needs Kids',img:'../assets/images/flutter_quiz_app.jpg'},
    {id:7, categorie:'mobile',project:'Taksk Managment App using Flutter and GO',img:'../assets/images/flutter_task.jpeg'},
    {id:8, categorie:'Full',project:'FullStack Twitter Clone App Using Mern',img:'../assets/images/twitter_clone.jpeg'},
    {id:9, categorie:'Full',project:'FullStack Ecommerce App using Mern',img:'../assets/images/ecommerce.jpeg'},
    {id:10, categorie:'Full',project:'FullStack Ecommerce App using Mern',img:'../assets/images/chat_app1.jpeg'},
    {id:11, categorie:'react',project:'Todos App using React',img:'../assets/images/prayer_app.jpeg'},
    {id:12, categorie:'mobile',project:'Book Car Maintenance App Base on ML',img:'../assets/images/prayer_app.jpeg'},
    {id:13, categorie:'js',project:'Snake Game using Js & Html & Css',img:'../assets/images/snake01.png'},
    {id:14, categorie:'js',project:'Tic-Tac-Toe Game using Js & Html & Css ',img:'../assets/images/tic_tac.jpg'},
    {id:15, categorie:'js',project:'Paper Collar Game using Js & Html & Css ',img:'../assets/images/paper.jpeg'},
    {id:16, categorie:'js',project:'Memory Game App using Js & Html & Css ',img:'../assets/images/memory_game01.jpeg'},
    {id:17, categorie:'js',project:'Quiz Game App using Js & Html & Css ',img:'../assets/images/quiz.png'},   
]